### ISSUE TITLE
Request for a v0.69.5 w/ LLVM v19.1 support

### ISSUE THREAD

**Issue by justsmth** [rust-lang/rust-bindgen#2945]
## Context

[aws-lc-sys](https://github.com/aws/aws-lc-rs) uses bindgen 0.69 for bindings generation.  Because [our MSRV needs to remain at 1.63](https://crates.io/crates/aws-lc-rs/versions) (at least for now), we are unable to depend on bindgen v0.70, which has an [MSRV of 1.70](https://crates.io/crates/bindgen/versions).

### Problem

See issue in our repo here: https://github.com/aws/aws-lc-rs/issues/476

When a consumer's build environment is using LLVM v19.1 and the "bindgen" feature of our package is enabled, the build breaks with a cryptic "cannot find function" error.  The bindings that are generated from such builds are missing all of our functions. (I suspect this relates to that fact that we use preprocessor macros to add prefixes to all of our function names.) 

Possible workarounds are: (-) asking the consumer to downgrade back to LLVM v18 or earlier, or (-) asking the consumer to install the latest version of `bindgen-cli` and set `AWS_LC_SYS_EXTERNAL_BINDGEN=1` in their build environment.

### Solution

I used "git bisect" to identify this commit as the one that resolves this problem: https://github.com/rust-lang/rust-bindgen/commit/600f63895f73c80d6bf7ff3c71b86a068d1663d2

To further verify, I cherry picked that commit on top of the commit for the v0.69.4 release to create a [release-v0.69.4-fixed branch](https://github.com/justsmth/rust-bindgen/commits/release-v0.69.4-fixed). I then successfully built `aws-lc-sys` w/ "bindgen" feature enabled using LLVM v19.1 against that branch of bindgen.

## Request

We ask that a **v0.69.5** release of bindgen be created that simply adds [the commit containing the fix](https://github.com/rust-lang/rust-bindgen/commit/600f63895f73c80d6bf7ff3c71b86a068d1663d2) onto v0.69.4.

* Both `clang_getSpellingLocation` and `clang_getFileLocation` appear to be available as far back as LLVM v5: https://github.com/hdoc/llvm-project/blob/release/5.x//clang/include/clang-c/Index.h#L598-L653

**Comment by pvdrz** [comment]
There you go:
- https://github.com/rust-lang/rust-bindgen/releases/tag/v0.69.5
- https://crates.io/crates/bindgen/0.69.5
- https://crates.io/crates/bindgen-cli/0.69.5

**Comment by emilio** [comment]
Thanks @pvdrz!
