### ISSUE TITLE
Failure to compile with `libclang 1.10` (default on ubuntu 20.04)

### ISSUE THREAD

**Issue by jalil-salame** [rust-lang/rust-bindgen#3169]
`bindgen` works with versions <0.71.0 on ubuntu 20.04 with libclang 1.10, but fails with the following error, when upgrading:

```log
error: linking with `cc` failed: exit status: 1
  |
  = note: [args ommitted]
  = note: some arguments are omitted. use `--verbose` to show all linker arguments
  = note: /usr/bin/ld: /home/ubuntu/Work/scone/target/release/deps/libbindgen-a3850525c18e938f.rlib(bindgen-a3850525c18e938f.bindgen.b6c67aa9f76b572c-cgu.09.rcgu.o): in function `bindgen::clang::Type::atomic_value_type':
          bindgen.b6c67aa9f76b572c-cgu.09:(.text._ZN7bindgen5clang4Type17atomic_value_type17hb225d9a718e76c71E+0x4d): undefined reference to `clang_Type_getValueType'
          collect2: error: ld returned 1 exit status

  = note: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#rustc-link-lib)
```

Proposed fix: Explicitly report lack of support for libclang <11 (20.04 is EOL in April so it shouldn't be a problem)

**Comment by emilio** [comment]
Ah, so this was fallout from 39232cc6e... But anyways, seems fine to close for now as we're past the EOL date. Thanks for the report tho!
