### ISSUE TITLE
__BindgenUnionField definition was missing from generated code even when in use

### ISSUE THREAD

**Issue by aleozlx** [rust-lang/rust-bindgen#1457]
### Input C/C++ Header

> Disclaimer: I know you don't want #include in the example, but this issue involves #include to be able to reproduce.

```C++
// Copyright 2014-2015 Isis Innovation Limited and the authors of gSLICr
union GiveMeUnion { int _; };
#include "engines/gSLICr_core_engine.h"
```

### Bindgen Invocation

```Rust
let bindings = bindgen::Builder::default()
    .header("gSLICr/gSLICr_Lib/gSLICr.h")
    .enable_cxx_namespaces()
    .whitelist_type("gSLICr::engines::core_engine")
    // .whitelist_type("GiveMeUnion")
    // .disable_untagged_union()
    .clang_args(&["-x", "c++", "-std=c++11", "-I", "/opt/cuda/include"])
    .generate()
    .expect("Unable to generate bindings");

let out_path = PathBuf::from("target/gen");
bindings.write_to_file(out_path.join("bindings.rs"))
    .expect("Couldn't write bindings!");
```

### Actual Results

The `__BindgenUnionField` was simply **not defined** in the generated code, even though **in use**, unless I uncomment the two lines in the bindgen invocation. My thinking was that maybe the unions appeared too far down the road (to clarify, these unions requires the BindgenUnionField implementation) and whether to emit the definition maybe only checked at a point very early. So I added & whitelisted that dummy union `GiveMeUnion` as a workaround. Everything else was fine in the generated code.

```
error[E0412]: cannot find type `__BindgenUnionField` in module `root`
  --> src/../target/gen/bindings.rs:27:23
   |
27 |                 root::__BindgenUnionField<root::ORUtils::Vector2___bindgen_ty_1__bindgen_ty_1<T>>,
   |                       ^^^^^^^^^^^^^^^^^^^ not found in `root`

error[E0412]: cannot find type `__BindgenUnionField` in module `root`
  --> src/../target/gen/bindings.rs:29:23
   |
29 |                 root::__BindgenUnionField<root::ORUtils::Vector2___bindgen_ty_1__bindgen_ty_2<T>>,
   |                       ^^^^^^^^^^^^^^^^^^^ not found in `root`
```

### Expected Results

When I uncomment the two lines in the bindgen invocation it works, but I was expecting this to work without those.

**Comment by emilio** [comment]
Yeah, this should work, I can see where the bug is, this looks broken since e7fa2895582435b59dfb1ac960167b0876f8da55.

Thanks for the report!

**Comment by emilio** [comment]
Reduced test-case would be:

```cpp
// bindgen-flags: --rust-target 1.0 --enable-cxx-namespaces

namespace foo {
  union Bar {
    int foo;
    int bar;
  };
}
```
