### ISSUE TITLE
Upgrade to 0.55: r_debug__bindgen_ty_1 not found in this scope.

### ISSUE THREAD

**Issue by vext01** [rust-lang/rust-bindgen#1880]
### Input C/C++ Header

It's just an include of `<link.h>` on a Debian 10 system. [Expanded file here](https://gist.github.com/vext01/18d2f642c58f41a3f1c6b47c32a82156)

### Bindgen Invocation

```Rust
let bindings = bindgen::Builder::default()                                                     
    .header(WRAPPER_HEADER)                                                                                                              
    .generate()                                                                                
    .expect("bindgen failed");
```

### Actual Results

Compilation fails:
```
error[E0412]: cannot find type `r_debug__bindgen_ty_1` in this scope
    --> /home/vext01/research/yorick/bindgen-bug/target/debug/build/phdrs-8186bba3cfb0801b/out/bindings.rs:7710:18
     |
7710 |     pub r_state: r_debug__bindgen_ty_1,
     |                  ^^^^^^^^^^^^^^^^^^^^^ not found in this scope
```

Any ideas?

**Comment by emilio** [comment]
Hmm, probably a regression from #1850. Thanks for filing!

Reduced test-case:

```c
typedef unsigned long long Elf64_Addr;

struct r_debug
  {
    int r_version; /* Version number for this protocol.  */

    struct link_map *r_map; /* Head of the chain of loaded objects.  */

    /* This is the address of a function internal to the run-time linker,
       that will always be called when the linker begins to map in a
       library or unmap it, and again when the mapping change is complete.
       The debugger can set a breakpoint at this address if it wants to
       notice shared object mapping changes.  */
    Elf64_Addr r_brk;
    enum
      {
 /* This state value describes the mapping change taking place when
	   the `r_brk' address is called.  */
 RT_CONSISTENT, /* Mapping change is complete.  */
 RT_ADD, /* Beginning to add a new object.  */
 RT_DELETE /* Beginning to remove an object mapping.  */
      } r_state;

    Elf64_Addr r_ldbase; /* Base address the linker is loaded at.  */
  };
```

**Comment by emilio** [comment]
https://github.com/rust-lang/rust-bindgen/pull/1882 has a fix.

**Comment by vext01** [comment]
Thanks!

**Comment by emilio** [comment]
0.55.1 has this fix, thank you again for reporting it.
