### ISSUE TITLE
objc_interface_type.h generates non-compiling code.

### ISSUE THREAD

**Issue by emilio** [rust-lang/rust-bindgen#1954]
It generates:

```rust
#[repr(transparent)]
#[derive(Clone)]
pub struct Foo(pub id);

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FooStruct {
    pub foo: Foo,
}
```

So either the interface pointer should derive Copy, Debug and co, or we should prevent structs like that from deriving them.

This particular case is a regression from 840b738ec I think, cc @simlay. I'm commenting out the struct in #1953 to have macos CI again.

**Comment by emilio** [comment]
objc_whitelist has the same issue.

**Comment by emilio** [comment]
That last one was broken by 4562ef97c08d63f88026aea5b63ddda9c0170d31 (should've reviewed the test update a bit more carefully)

**Comment by simlay** [comment]
Ah yes, the `Copy` derive removed from #1883 objective-c structs broke the derive `Copy` in the C struct. Come to think of it, I think https://github.com/RustAudio/coreaudio-sys/pull/33#issuecomment-695358024 is this same issue. I'll admit that I've come to like how not deriving `Copy` for the objective-c stuff has caused me to write more ergonomic objective-c rust but if it produces broken bindings, it's not worth it.

I'm a little confused why we didn't catch it and why #1952 brings it to light though.

**Comment by emilio** [comment]
Another failure, from objc_template.h:

```
error[E0310]: the parameter type `ObjectType` may not live long enough                                                                                                                                                                   
  --> /Users/runner/work/rust-bindgen/rust-bindgen/tests/expectations/tests/libclang-4/objc_template.rs:34:9
   |
29 | pub trait IFoo<ObjectType>: Sized + std::ops::Deref {
   |                ---------- help: consider adding an explicit lifetime bound...: `ObjectType: 'static`
...
34 |         msg_send!(*self, get)
   |         ^^^^^^^^^^^^^^^^^^^^^ ...so that the type `*mut ObjectType` will meet its required lifetime bounds
```

These were covered up because we were running the `test` job on macos, but not the `expectations` job (which is basically `cd tests/expectations && cargo test`).

I noticed it, fixed it, and found all this fun :)

**Comment by simlay** [comment]
> I noticed it, fixed it, and found all this fun :)

Well, I feel a little bad. I wish I would have known that we didn't run the `expectations` job in macos and would have added it to CI back in like February. I'm glad we're uncovering the issues though.

**Comment by emilio** [comment]
Right, right, this was a surprise to me as well, but glad to find these indeed :)
