### ISSUE TITLE
Firefox fails to compile with Rust 1.84 + Bindgen 0.71.1 + LLVM LibC++

### ISSUE THREAD

**Issue by theoparis** [rust-lang/rust-bindgen#3116]
I've already reported this to Gentoo, only for it to get closed as a bindgen specific issue so I'm reporting this here now:

Firefox's servo style crate fails to rebuild with bindgen errors. I'm not sure the best way to fix this but it is causing me to have to use chromium through Nix without gpu acceleration due to there being no firefox-bin package for aarch64...

```
8 4:44.46 error[E0412]: cannot find type `_Allocator` in this scope
8 4:44.46      --> /var/tmp/portage/www-client/firefox-135.0/work/firefox_build/aarch64-unknown-linux-gnu/release/build/style-0b4840547393bb86/out/gecko/structs.rs:68488:80
8 4:44.46       |
8 4:44.46 68488 |             pub mVector: root::__BindgenUnionField<*mut root::std::__1::vector<_Allocator>>,
8 4:44.46       |                                                                                ^^^^^^^^^^ not found in this scope
8 4:44.46       |
8 4:44.46 help: you might be missing a type parameter
8 4:44.46       |
8 4:44.46 68486 |         pub struct SmallPointerArray_Element<T, _Allocator> {
8 4:44.46       |                                               ++++++++++++
```
See https://bugs.gentoo.org/949356 for more information, it contains the full build logs.

**Comment by emilio** [comment]
`mozilla::SmallPointerArray` is already opaque [here](https://searchfox.org/mozilla-central/rev/d1fbe983fb7720f0a4aca0e748817af11c1a374e/layout/style/ServoBindings.toml#303). If you add `mozilla::SmallPointerArray_Element` (or `mozilla::SmallPointerArray::Element`, forget which one is the right syntax) there, does it work?

This is probably worth tracking upstream in https://bugzilla.mozilla.org tho.

**Comment by LinuxUserGD** [comment]
Already fixed upstream
https://bugzilla.mozilla.org/show_bug.cgi?id=1941479
