### PR TITLE
Restrict newtype constant wrapping to actual type aliases

### LINKED ISSUE #3303: Constant generation for my project broken by PR #3288
Constant generation for my project got broken by PR #3288. I can't copy-paste a repro directly because of closed source blah blah blah, will try to get a minimal repro and post it here in the next week or so. But the general pattern looks like this:

* We have some proprietary C headers and we're running bindgen to generate rust bindings to them
* Headers have constants like `#define FooBar 0x00000000`
* Expectation: bindgen should create a constant like `pub const FooBar: u32 = 0;`. Bindgen actually does that prior to #3288
* Post #3288, bindgen creates this: `pub const FooBar: u32 = u32(0);`
* This fails to compile with the error: `error[E0423]: expected function, found builtin type `u32``
* We're using bindgen as a library, calling it from `build.rs`

Here is the essence of our bindgen config (I tried to remove non-relevant stuff):

```
let mut builder = bindgen::Builder::default()
        .derive_default(true)
        .prepend_enum_name(false)
        .parse_callbacks(Box::new(bindgen::CargoCallbacks::new()))
        .default_enum_style(bindgen::EnumVariation::NewType {
            is_bitfield: false,
            is_global: false,
        })
        .default_alias_style(bindgen::AliasVariation::NewType)
        .generate_cstr(true)
        .no_copy("xxx") // in reality a bunch of regexes
        .type_alias("yyy") // in reality a bunch of regexes
        .merge_extern_blocks(true)
        .derive_debug(false)
        .impl_debug(false)
        .parse_callbacks(Box::new(AddDerivesCallbacks::new())); // these callbacks just add some traits to certain types based on regexes
```

### PR DESCRIPTION
**Pull request by armoha**
Fixes #3303

`alias_style` helper method fall backs to `ctx.options().default_alias_style` without checking if the item is actually a typedef/alias, resulting in matching built-in primitives to new type variant. The fix uses `ItemResolver` and `.through_type_refs()` to unwrap C type qualifiers (e.g. `const`, `volatile`) and verifies that the type kind is alias.

### CODE REVIEW

**Review by emilio — APPROVED** [review]
Thanks!

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust-bindgen/3390/4609f3fdd5d4c66ea67a6103a7850989c612273e..8edd7a3a5b102020ae08989fa26e1cf6bec57fcb)*
